
<div class="login pt-3 pb-3 container mt-5 d-flex justify-content-around">
    
    <div class="col-md-6">
        <? if(isset($_GET['cadastro']) && $_GET['cadastro'] == 'success'): ?>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <strong>Eba! </strong>Cadastro realizado com sucesso!<br>
            Faça login para continuar.
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
    <? endif ?>
        <form method="post" action="/autenticar">
          <h1 class="text-center">Login</h1>
          <div class="form-group">
            <label for="email">Email</label>
            <input name="email" type="email" class="form-control" id="email" placeholder="Digite seu email">
          </div>
          <div class="form-group">
            <label for="senha">Senha</label>
            <input name="senha" type="password" class="form-control" id="senha" placeholder="Digite sua senha">
          </div>
          <button type="submit" class="btn-login btn btn-block mb-2">Entrar</button>
          
            <? if(isset($_GET['login']) && $_GET['login'] == 'erro'): ?>
            <span class="text-danger" style="font-size: 1.2em;">Verifique se seus dados foram preenchidos corretamente.</span>
            <? endif ?>
        </form>
    </div>
</div>

